on: [pull_request]

jobs:
  accessibility_job:
    runs-on: ubuntu-latest
    name: Accessibility tests
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run a11y tests 
      id: a11y
      uses: omboo/a11y-action@v0.2.4
      with:
        urls: 'http://omboo.io'
        fail-on-error: true
        install: true
